-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceReaders/maintenance/db/sql/bs_readers.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_readers (
  readers_id SERIAL NOT NULL,
  readers_user_id INT NOT NULL,
  readers_user_name TEXT DEFAULT '' NOT NULL,
  readers_page_id INT NOT NULL,
  readers_rev_id INT NOT NULL,
  readers_ts VARCHAR(16) DEFAULT '' NOT NULL,
  PRIMARY KEY(readers_id)
);

CREATE INDEX readers_user_id ON bs_readers (readers_user_id);

CREATE INDEX readers_page_id ON bs_readers (readers_page_id);

CREATE INDEX readers_rev_id ON bs_readers (readers_rev_id);

CREATE INDEX readers_user_name ON bs_readers (readers_user_name);

CREATE INDEX readers_ts ON bs_readers (readers_ts);
