-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceReaders/maintenance/db/sql/bs_readers.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_readers (
  readers_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  readers_user_id INTEGER UNSIGNED NOT NULL,
  readers_user_name BLOB DEFAULT '' NOT NULL,
  readers_page_id INTEGER UNSIGNED NOT NULL,
  readers_rev_id INTEGER UNSIGNED NOT NULL,
  readers_ts VARCHAR(16) DEFAULT '' NOT NULL
);

CREATE INDEX readers_user_id ON /*_*/bs_readers (readers_user_id);

CREATE INDEX readers_page_id ON /*_*/bs_readers (readers_page_id);

CREATE INDEX readers_rev_id ON /*_*/bs_readers (readers_rev_id);

CREATE INDEX readers_user_name ON /*_*/bs_readers (readers_user_name);

CREATE INDEX readers_ts ON /*_*/bs_readers (readers_ts);
